### ISSUE TITLE
Invalid URL for SDK download

### ISSUE THREAD

**Issue by kevinDespoulains** [cross-solutions/install-flutter-sdk#4]
It seems that the URL for Flutter Download as changed :

```
Starting: Flutter Install
==============================================================================
Task         : Install Flutter SDK
Description  : Installs the Flutter SDK and add it to your 'PATH' environment. You can then run 
flutter commands in succeeding tasks using the command line.
Version      : 0.2.0
Author       : contrix09
Help         : Go to http://flutter.io for more information.
==============================================================================
Downloading latest sdk from https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v.17.0-stable.zip
Downloading: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v.17.0-stable.zip
##[error]Unexpected HTTP response: 404
Finishing: Flutter Install
```

URL https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v.17.0-stable.zip does not work.

URL https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.17.0-stable.zip does work.

It looks like the 'v' before the version number is not used anymore.
Can you take a look at it?

Thank you.

**Comment by dustincatap** [comment]
Hi. Will check on this.

**Comment by dustincatap** [comment]
Fixed the download URL. Update the extension to version `0.2.4`

![image](https://user-images.githubusercontent.com/56006524/81757738-72f6e100-94f2-11ea-96f7-f9a20f904381.png)
