### ISSUE TITLE
Pin version of Flutter

### ISSUE THREAD

**Issue by teamtam** [cross-solutions/install-flutter-sdk#6]
You can currently select the Stable|Beta|Dev|Master release channel. It would be great if there is the option to enter a specific version of Flutter.

**Comment by PopovVA** [comment]
@teamtam Hey. I've created PR https://github.com/cross-solutions/install-flutter-sdk/pull/10

Hope it will merged successfully

**Comment by dustincatap** [comment]
Closed. Released new version 0.2.5. Thanks!
